id: I6A2A26E6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:50:42+00:00'
last_modified: '2022-06-08T06:42:41.203088+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23609
  title: ཞེ་ཆེན་དབོན་སྤྲུལ་འགྱུར་མེད་མཐུ་སྟོབས་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA4D:
      image_group_id: I2285
      title: ''
      total_pages: 268
      order: 1
      base_file: CA4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
