id: P006766
initial_creation_type: ocr
source_metadata:
  id: bdr:W23609
  title: ཞེ་ཆེན་དབོན་སྤྲུལ་འགྱུར་མེད་མཐུ་སྟོབས་རྣམ་རྒྱལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    4e9644caa1ad4becbd90ad7c25556247:
      image_group_id: I2285
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
